name: loans
description: "bank_nasser_loans_application"
publish_to: 'none'
version: 1.0.0+1
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/images/bank_nasser.png"
  min_sdk_android: 21

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  firebase_core: ^2.15.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.9.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/bank_nasser.png
# ⬇️⬇️⬇️ MOVE THIS SECTION TO ROOT LEVEL (same indentation as "name" and "dependencies") ⬇️⬇️⬇️
